### PR TITLE
Updated to service fabric 3.3.664 and added implementation of CreateNonIServiceProxy

### PR DESCRIPTION
**Pull request by PixelByProxy**
The changes to the interface on pull request https://github.com/microsoft/service-fabric-services-and-actors-dotnet/pull/131/ is not compatible. Updated nuget packages and implemented interface with a NotSupportedException.

### CODE REVIEW

**Comment by yantang-msft** [comment]
LGTM, please sign the agreement so we can take the PR and release a new version.

**Comment by abhikmitra** [comment]
Thanks , we need this too  👍

**Comment by PixelByProxy** [comment]
Working on getting company approval for CLA.

**Comment by PixelByProxy** [comment]
All set. Thanks!

**Pull request merged**
